### ISSUE TITLE
SG ToDo

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#153]
_NB. Subject to discussion and SG feedback_ @docuracy 

- [ ] Tileset Creation Testing see #155
- [ ] API see #156 
- [ ] Gallery hover behavior see #163
- [ ] Popups & Modals #164
- [ ] Bug/Snag Inventory #165
**As time permits:**
- [ ] Vision of Britain see #166
