### ISSUE TITLE
Tileset Management Console

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#222]
### Files
- `webpack/js/tileset-tools.js`

### URLs
- path('tileset_management/', main.views.TilesetListView.as_view(), name='tools-tilesets')
- path('tileset_generate/<str:category>/<int:id>/', main.views.tileset_generate_view, name='tileset_generate')
- path('tileset_task_progress/', main.tasks.get_tileset_task_progress, name='tileset_task_progress')

### Tasks
- `main.tasks.request_tileset`
- `main.tasks.process_tileset_request`
- `main.tasks.get_tileset_task_progress`
- `main.tasks.needs_tileset`

- [x] Recent changes to JavaScript seem to have broken the progress monitoring.
    - [x] First request and some subsequent ones get a 504 timeout, but tileset _is_ generated.
    - [x] _Some_ subsequent requests get 200 OK, but a `null` task_id in response and no tileset generation.
    - [x] There is only one call to tileset_task_progress, immediately after the first tileset generation request.
- [x] Some tileset requests fail, e.g.:
    - [x] Tileset creation failed for datasets-1223 because the metadata include double-quotes which need to be escaped in the tippecanoe command
    - [x] Tileset creation failed for datasets-1234 because all features have `null` geometry
- [x] Some "Needs Tileset" requests are still _very_ slow, for example:
    - [x] 15 "HGIS de las Indias territorios" (3m+ coordinates, tileset is available): perhaps function can return after exceeding threshold?
    - [x] 677 "My Dataset" [Problem was due to `cluster_geometries` failing for nested null geometries and `needs_tileset` failing for null place.geom.geom]
- [x] Tooltips are not clearing automatically on click of "Generate Tileset": force clearing on all clicks.
- [x] ~Sort on Title, not ID.~
- [x] Add column for `published` status in order to prioritise? Maybe discourage or even disallow generation for unpublished data?
- [x] Table entries should be created for orphan tilesets to facilitate their deletion (maybe they are already, e.g. 40 "Atlas of Mutual Heritage"?)

**Comment by docuracy** [comment]
In anticipation of v3 going live, I've modified `send_tileset_request` which was always giving 'dev.whgazetteer.org' as the base url for TILEBOSS to make requests for mapdata. The base url is now derived from `settings.URL_FRONT`:

```
        url_base = urlparse(settings.URL_FRONT).netloc # URL_FRONT might be http://dev.whgazetteer.org/ or http://whgazetteer.org/
        url_base = 'dev.whgazetteer.org' if 'whgazetteer.org' not in url_base else url_base
        geoJSONUrl = f"https://{url_base}/{category}/{id}/mapdata/?variant=tileset"
        print(f"geoJSONUrl: {geoJSONUrl}")
        data = {
            "geoJSONUrl": geoJSONUrl,
        }
```
