### ISSUE TITLE
Yet another TODO list

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#231]
Home
----
- [x] contact modal from sends ok, but modal mask remains [Fixed that problem, but found another: form submits to wrong URL subsequent to a failed submission and form refresh]
- [x] #239
- [x] top 2 blurbs say far too little, imho

Search
------
- [x] Uncaught DOMException: Failed to execute 'setItem' on 'Storage': Setting the value of 'last_search' exceeded the quota.
	- localStorage.clear() and it was ok
- [x] ~results: container extends below window~ I think existing is the best compromise for variety of screen sizes: map has min-height of 400px, and results max-height of 40vh. 
- [x] "place portal" link sometimes delivers the single record detail page
- [ ] place types and place categories filters are largely redundant
	- add count of categories post search?
- [x] #238

Portal
------
- [x] content extends well below 945px tall browser window 
	- should be like the ds_browse page, e.g.
- [x] #234

Dataset pub (ds_browse)
-------------------------------
- [ ] ~#233~
	- ~e.g. https://dev.whgazetteer.org/datasets/62/places~
- [x] some markers far too small (e.g. https://dev.whgazetteer.org/datasets/693/places)
	- orange against earth tones not best choice (they are red elsewhere)
- [x] initial display of polygons invisible, nice highlight on hover (e.g. https://dev.whgazetteer.org/datasets/1155/places)
- [x] problems: 
	- ds 2, 12 (black, owtrad): TypeError: Cannot read properties of undefined (reading 'length'); both display on home page
- [x] window width < 1200px hides add-to-collection if start/end
- [x] #237
- [ ] published datasets need images, better descriptions, essays, time slider choice <= Ali

Place collection pub (place_collection_browse)
---------------------------------------------
- [x] # 139 [(Russian, East European, and Eurasian Studies) ](https://dev.whgazetteer.org/collections/139/browse_pl) fails to load: 500, "TypeError at /mapdata/collections/139/ Invalid type encountered in the arguments."

Dataset collection pub (ds_collection_browse)
---------------------------------------------
- [x] #'s 325, 172 ok; #'s 28, 2 not ok (2 is low priority)
	- NB whereas datasets theoretically must now be indexed, in practice they needn't be (e.g # 25 Ukraine, # 10 Central Asia)
		- this is enforced only in the ds_select option filtering to only 'indexed'
- [ ] ~change of composition (add, remove dataset) requires new tileset, cache file~ Part of #221 

Gallery
-------
- [x] #236
- [x] need to filter out datasets with 'core' = True (e.g. TGN)
- [ ] differentiate place and dataset collections?
- [ ] some datasets created purely for collections - belong in gallery? (e.g. Frankopan*)

Tileset admin
-------------
- [x] #232

installation.md
---------------
- [x] #243

**Comment by kgeographer** [comment]
an old TODO, closing
