### ISSUE TITLE
The last pre-launch TODO list

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#252]
- [ ] collections in gallery
  - [ ] collection creator(s) [@kgeographer]
  - [ ] differentiate place and dataset collections [@kgeographer]
- [x] spinners when loading big things could use a message like "Rendering..."; or maybe "Rendering {n} places in {n} datasets" if those values are available [@docuracy]
- [x] legend appears on Dataset Collection pub page map - not relevant for dscolls [@docuracy] [Fixed by removing `relations` from generation of `mapdata`]
- [x] Dataset Collection `mapdata` fails through absence of `fclasses` from FamilyPlace pseudo-model

**Comment by docuracy** [comment]
I've been thinking about labelling the spinners for big things, but in fact once all of the chunky mapdata is filecached the load times seem to be so swift that I don't think the labels would be visible long enough for them to be read. I'm running a management command now to generate cache files for any mapdata that takes longer than half a second to generate - we'll see once that's completed.

**Comment by docuracy** [comment]
... aaargh forgot to restart celery worker container AGAIN

**Comment by kgeographer** [comment]
> I've been thinking about labelling the spinners for big things, but in fact once all of the chunky mapdata is filecached the load times seem to be so swift that I don't think the labels would be visible long enough for them to be read. I'm running a management command now to generate cache files for any mapdata that takes longer than half a second to generate - we'll see once that's completed.

I put that on the list after waiting several seconds for a dataset collection to load - probably clicked from the gallery, not certain. Agree that load times are radically better than when we first wired up to the "real" data.

**Comment by kgeographer** [comment]
an old TODO - closing
