### ISSUE TITLE
Vespa Migration Plan

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#408]
*Plan under development*

## Preparation 

- Develop scripts for:
    - [ ] extraction of PLACE records from existing Datasets and Collections.
    - [ ] mounting exodatasets as PLACE records.
    - [ ] cloning of existing database.
    - [ ] cloning of existing datafiles.

## Local Development

It should be possible to develop and run the new system in local Docker networks before cloning through GitHub to the remote servers.

### Destined for Aalborg-MEHDIE server

- Extend existing Docker network to include:
    - [ ] Vespa
    - [ ] Portainer
    - [ ] Tileserver 
    - [ ] Monitoring tools

### Destined for Digital Ocean Server (replication)
- Docker network:
    - [ ] Portainer 
    - [ ] Vespa

## Preparation of remote servers

- [ ] SSH keys
System software
- [ ] SSH management
- [ ] SSL certificate management
- [ ] Docker

**Comment by docuracy** [comment]
### Tasks

- [ ] Configure Wordpress and migrate content
- [ ] Configure nodeAffinity to determine pod placement across the cluster
