### ISSUE TITLE
Dataset Gallery

### ISSUE THREAD

**Issue by kgeographer** [WorldHistoricalGazetteer/whg3#61]
- http://localhost:8001/datasets/gallery
- `/datasets/templates/datasets/ds_gallery.html`

**TODO**

**Features**
- [x] Use same code for Collections - rewrite as API view incorporating existing `carousel_metadata` property
- [x] Paginate results - build page dynamically
- [x] Textbox filter (title and description only)
- [x] Dropdown region/country MULTI-selector filters (see https://whgazetteer.org/api/area_list/ and split by predefined|country)
- [x] Replace `throttle` with `lodash/debounce` (default settings) - see https://ellenaua.medium.com/throttle-debounce-behavior-lodash-6bcae1494e03. Also replace custom debounce function in `utilities.js`.
- [x] Fix layout of country filter Clear button, which detaches when screen is narrowed: see `formGroup.outerWidth();` solution [here](https://stackoverflow.com/questions/37943730/how-can-i-dynamically-resize-a-select2-input-to-be-the-same-width-as-the-selecte).
- [ ] Something wrong with selecting New Zealand, perhaps an International Date Line issue? Eastern tip of Russia is missing from geometry...
- [ ] Recode links in main menu - should be:

```
        ["Datasets","{% url 'datasets:dataset-gallery-type' gallery_type='datasets' %}"],
	["Collections","{% url 'datasets:dataset-gallery-type' gallery_type='collections' %}"]
```
- [x] Load country GeoJSON per country and only if/when selected in filter.
- [ ] The `DatasetGalleryView` is currently having to populate ccodes for predefined areas, which ought to be present in the database.
- [ ] Add author dropdown?

**Sorting** - handled by `DatasetGalleryView` to accommodate paginator
- [x] title (use -title for reverse)
- [x] numrows (use -numrows for descending)
- [x] earliest (MinMax[0] ascending, or -earliest for descending)
- [x] latest (MinMax[1] descending, or -earliest for ascending)
- [x] recently modified

**KG**
- [ ] style boxes
