### ISSUE TITLE
Toggle Sequence/Date sort & antlines [placecollection_browse.html]

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#66]
- Example: http://localhost:8001/collections/11/browse_pl
- /collection/templates/collection/place_collection_browse.html

**Comment by docuracy** [comment]
**TODO**

- [ ] Remove date filters when #dateline is hidden
- [ ] Re-code sequencer to cope with non-sequential and reverse-order lists
- [ ] Remove test console logging
- [ ] Test that operation of other pages is not disturbed by alterations to shared code
