### ISSUE TITLE
Alternative to hull [Home]

### ISSUE THREAD

**Issue by docuracy** [WorldHistoricalGazetteer/whg3#67]

**Comment by docuracy** [comment]
**TODO:**

- [ ] Scale the heatmap styling dynamically based on the datacollection `area` profile.
- [ ] Add plain hull display_mode option
- [ ] Default to unmodified FeatureCollection rendering
- [ ] Experiment with cluster-count elbow determination

**Comment by kgeographer** [comment]
there are now several alternatives to hull in deployment
